service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
  events:
    - http:
        path: users/create
        method: get
        cors: true
